import java.time.DayOfWeek;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 * Interface allows the entry of data by the user in a graphic way
 * @author Sebas
 */

public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * 
     * @param field
     * @param num
     * @param charAux
     * @return
     */
    public boolean validationLengthLetter(String field, int num, char charAux) {
        if (field.length() == num || (charAux < 'a' || charAux < 'z') && (charAux < 'A') | charAux < 'B') {
            return true;
        }
        return false;
    }

    /**
     * Controls the maximum number of characters entered in a numeric field
     * @param field It is the string imputed by the visual interface
     * @param num It is the length of numeric characters that the entered string must have
     * @param charAux Allows you to control the range of numeric values
     * @return True if the character imputed can be added
     */
    public boolean validationLengthNum(String field, int num, char charAux) {
        if (field.length() == num || (charAux < '0' || charAux > '9')) {
            return true;
        }
        return false;
    }

    /**
     * Controls that all the cells have the number of characters required in each format
     * Example day is 2 character 
     * @return True if all condition are met
     */
    public boolean validationInput() {

        if (txtPlateLetter.getText().length() == 3
                && txtPlateNumber.getText().length() == 4
                && txtDay.getText().length() == 2
                && Integer.parseInt(txtDay.getText()) <= 31
                && txtYear.getText().length() == 4
                && txtMinute.getText().length() == 2
                && Integer.parseInt(txtMinute.getText()) <= 60) {
            cleanFormatMessage();
            return true;
        }
        incorrectFormatMessage();
        return false;
    }

    /**
     * Display an incorrect format message in the interface 
     * Depend on the wrong data entered. Example hour, date, license plate
     */
    public void incorrectFormatMessage() {
        cleanFormatMessage();

        if (txtPlateLetter.getText().length() != 3 || txtPlateNumber.getText().length() != 4) {
            lblFormatPlate.setText("Incorrect format");
        }

        if (Integer.parseInt(txtDay.getText()) > 31 || txtDay.getText().length() != 2 || txtYear.getText().length() != 4) {
            lblFormatDate.setText("Incorrect format");
        }

        if (Integer.parseInt(txtMinute.getText()) > 60 || txtMinute.getText().length() != 2) {
            lblFormatTime.setText("Incorrect format");
        }
    }

    /**
     * Clears the format error messages in the interface 
     * This happens every time that the predict button is pressed
     */
    public void cleanFormatMessage() {
        lblFormatPlate.setText("");
        lblFormatDate.setText("");
        lblFormatTime.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnPredict = new javax.swing.JButton();
        txtPlateLetter = new javax.swing.JTextField();
        boxMonth = new javax.swing.JComboBox<>();
        boxHour = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMinute = new javax.swing.JTextField();
        txtPlateNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblFormatDate = new javax.swing.JLabel();
        lblFormatTime = new javax.swing.JLabel();
        lblFormatPlate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pico y Placa");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnPredict.setText("Predict");
        btnPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredictActionPerformed(evt);
            }
        });

        txtPlateLetter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlateLetterKeyTyped(evt);
            }
        });

        boxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        boxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLabel2.setText("Enter the license plate number (e.g., PBX-1234)");

        jLabel3.setText("Enter the date (in the format dd-MM-yyyy)");

        jLabel4.setText("Enter the time (in the format HH:mm)");

        txtDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDayKeyTyped(evt);
            }
        });

        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        jLabel5.setText("-");

        jLabel6.setText("-");

        jLabel7.setText(":");

        txtMinute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinuteKeyTyped(evt);
            }
        });

        txtPlateNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlateNumberKeyTyped(evt);
            }
        });

        jLabel8.setText("-");

        lblFormatDate.setForeground(new java.awt.Color(255, 0, 51));

        lblFormatTime.setForeground(new java.awt.Color(255, 0, 51));

        lblFormatPlate.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(boxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnPredict, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFormatTime)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPlateLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblFormatPlate))
                                .addGap(97, 97, 97)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(boxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFormatDate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(241, 241, 241)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblFormatDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblFormatPlate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlateLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblFormatTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnPredict)
                .addGap(74, 74, 74)
                .addComponent(btnExit)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredictActionPerformed

        String PlateLetter = txtPlateLetter.getText();
        String PlateNumber = txtPlateNumber.getText();
        String licensePlate = PlateLetter.concat("").concat("-").concat(PlateNumber);
        System.out.println(licensePlate);

        String day = txtDay.getText();
        String month = boxMonth.getSelectedItem().toString();
        String year = txtYear.getText();
        String dateStr = year.concat("").concat("-").concat(month).concat("-").concat(day);
        System.out.println(dateStr);
        //String dateStr = txtDay.getText();

        String hour = boxHour.getSelectedItem().toString();
        String minute = txtMinute.getText();
        String timeStr = hour.concat("").concat(":").concat(minute);
        System.out.println(timeStr);
        //String timeStr = txtMinute.getText();

        if (validationInput()) {
            DayOfWeek dayOfWeek = DayOfWeek.from(java.time.LocalDate.parse(dateStr));
            LocalTime time = LocalTime.parse(timeStr, DateTimeFormatter.ofPattern("HH:mm"));
            Car car = new Car(licensePlate);

            boolean canBeOnRoad = car.predictPicoPlaca(dayOfWeek, time);
            if (canBeOnRoad) {
                JOptionPane.showMessageDialog(null, "The car is allowed to be on the road");
            } else {
                JOptionPane.showMessageDialog(null, "The car is not allowed to be on the road");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Information is not correct, please look over the input formats");
        }

    }//GEN-LAST:event_btnPredictActionPerformed

    private void txtPlateNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlateNumberKeyTyped
        char charAux = evt.getKeyChar();
        if (validationLengthNum(txtPlateNumber.getText(), 4, charAux)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlateNumberKeyTyped

    private void txtDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayKeyTyped
        char charAux = evt.getKeyChar();
        if (validationLengthNum(txtDay.getText(), 2, charAux)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDayKeyTyped

    private void txtMinuteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinuteKeyTyped
        char charAux = evt.getKeyChar();
        if (validationLengthNum(txtMinute.getText(), 2, charAux)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMinuteKeyTyped

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char charAux = evt.getKeyChar();
        if (validationLengthNum(txtYear.getText(), 4, charAux)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtPlateLetterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlateLetterKeyTyped
        char charAux = evt.getKeyChar();
        if (validationLengthLetter(txtPlateLetter.getText(), 3, charAux)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtPlateLetterKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxHour;
    private javax.swing.JComboBox<String> boxMonth;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPredict;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFormatDate;
    private javax.swing.JLabel lblFormatPlate;
    private javax.swing.JLabel lblFormatTime;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtMinute;
    private javax.swing.JTextField txtPlateLetter;
    private javax.swing.JTextField txtPlateNumber;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
